import {build} from 'esbuild';
import assert from 'node:assert/strict';
const bundle=await build({stdin:{contents:"export * as THREE from 'three';export * from './src/mining/rig';export * from './src/mining/outcrop';export * from './src/game';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const {THREE,createMining,createOutcrop,freshState,gather,serialize,deserialize}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const state=freshState();state.outcrops=[{id:1,born:0,hits:6,side:1}];
const scene=new THREE.Scene(),body=new THREE.Group();scene.add(body);
let art=createOutcrop(state.outcrops[0]);scene.add(art.root);art.root.position.z=5;
let awards=0;
const rig=createMining(body,scene,()=>art,()=>state.outcrops.map(o=>o.id),(id,precise)=>{const ok=gather(state,id,precise);if(ok){awards++;if(state.outcrops.length)art.damage(state.outcrops[0].hits);else {art.dispose();art=undefined;}}return ok;});
const run=()=>{for(let i=0;i<110;i++)rig.update(.01);};
rig.update(0);const initial=state.resources.stone;
rig.quickStrike();rig.quickStrike();run();assert.equal(awards,1);assert.equal(state.resources.stone,initial+2);assert.equal(art.chunks.filter(c=>c.visible).length,5);
assert.equal(deserialize(serialize(state)).outcrops[0].hits,5);
rig.begin(1);rig.cancel();run();assert.equal(awards,1);
art.root.updateWorldMatrix(true,true);const weak=art.weakPoints[0];const point=art.root.localToWorld(weak.point.clone());const ray=new THREE.Raycaster(point.clone().addScaledVector(weak.normal,4),weak.normal.clone().negate());
rig.begin(1,ray);rig.release();run();assert.equal(state.resources.stone,initial+5);
for(let i=0;i<4;i++){rig.quickStrike();run();}assert.equal(awards,6);assert.equal(state.outcrops.length,0);assert.equal(rig.busy,false);
rig.quickStrike();run();assert.equal(awards,6);assert.equal(gather(state,1,true),false);
const bounds=[];for(let id=0;id<4;id++){const a=createOutcrop({id,born:0,hits:6,side:1});bounds.push(new THREE.Box3().setFromObject(a.root).getSize(new THREE.Vector3()).toArray());a.damage(1);assert.equal(a.chunks.filter(c=>c.visible).length,1);a.dispose();}assert.equal(new Set(bounds.map(JSON.stringify)).size,4);
console.log('PASS Mining single-impact awards, seam bonus, cancellation, final break, save compatibility, and varied destructible silhouettes');
